---
title: "Tyler Lowry"
format:
  html:
    toc: false
  pdf:
    pdf-engine: weasyprint
    margin-top: 0.25in
    margin-bottom: 0.25in
    margin-left: 0.5in
    margin-right: 0.5in
css: cv.css
execute:
  echo: false
format-links: [pdf]
---

```{python}
#| tags: [parameters]
email = 'tjlowry02@gmail.com'
github = 'tjlowry'
linkedin = 'tylerj-lowry'
telephone = '480-297-6545'

```

```{python}
import polars as pl
from IPython.display import Markdown
```

____
:::: {.columns}

::: {.column width="22%"}
`{python} Markdown(f'[{email}](mailto:{email})')`
:::

::: {.column width="1%"}
:::

::: {.column width="22%"}
`{python} Markdown(f'[github.com/{github}](https://github.com/{github})')`
:::

::: {.column width="1%"}
:::

::: {.column width="22%"}
`{python} Markdown(f'[linkedin.com/in/{linkedin}](https://www.linkedin.com/in/{linkedin}/)')`
:::

::: {.column width="1%"}
:::


::: {.column width="22%"}
`{python} Markdown(f'[{telephone}](tel:{telephone})')`
:::


::::

____
## Education

**Brigham Young University-Idaho** [Apr 2025]{.cvdate}  
BS, Data Science - Accounting Minor – Machine Learning Certificate  
Rexburg, ID  
- GPA: 3.89
- Member of Data Science Society

## Skills

**Advanced:**
- R, Python, Pandas, Polars, SQL
- Machine Learning, Demand Forecasting, TensorFlow, Scikit-Learn, Time Series
- Tableau, Power BI

**Competent:**
- HTML, CSS, JavaScript, PHP, PySpark, C#
- APIs, Data Pipelines, Database Managemet, PySpark, 
- Excel, VBA, Adobe Suite

## Work Experience

### Machine Learning Engineer Intern
***PIC Business Systems*** [June 2023 – Present]{.cvdate}  
San Antonio, TX

- Developed a 90-day sales forecasting ensembled model and an interactive dashboard for product performance, resulting in a 30% improvement in median forecast MAPE
- Enhanced data quality by integrating external factors such as weather and date, using APIs and Pandas to create additional features for the model
- Automated monthly forecasting and database updates by leveraging AWS Lambda and S3 Buckets, enabling easy access to forecasts and reducing manual efforts

### TA/Tutor
***BYU-Idaho*** [April 2024 – Present]{.cvdate}  
Rexburg, ID

- Served as a teaching assistant and tutor for "Intro to Programming," "Math for the Real World," "Data Wrangling and Visualization," "Data Science Programing," and "Biostatistics"
- Led group and one-on-one tutoring sessions focused on Python, R, Excel, and arithmetic
- Provided general data science support at the Data Science Tutoring Lab, assisting students across various data science and mathmatics courses with Python, R, and other coursework-related questions

### Team Lead/Developer
***BYU-Idaho McKay Maclab*** [Jan 2023 – Present]{.cvdate}  
Rexburg, ID

- Collaborated with team of 4 in full stack developments of Maclab and Library website and 3D printing queue for patron use, including TTL policies
- Conducted interviews, reviewed resumes to screen candidates, and provided training to new employees
- Facilitated weekly meetings to discuss goals, track task progress, and deliver short training sessions to the team
- Designed interactive streamlit dashboards to track KPI performance, resulting in a 14% average improvement across all metrics

### Intern
***George W. Lowry Inc.*** [Sept 2023 – Dec 2023]{.cvdate}  
Salida, CA

- Optimized SQL queries and database architecture, reducing report generation time from 2+ hours to 5 minutes through improved indexing and query restructuring
- Identified and implemented an AWS EC2 instance, increasing computing power while lowering costs, reducing server crashes, and improving efficiency
- Developed a CRM using a PHP framework, enhancing location data tracking and streamlining communication between salesmen and delivery drivers for improved logistics